export type SettingsAreaId =
  | 'home'
  | 'data'
  | 'lab'
  | 'trading'
  | 'notifications'
  | 'system'
  | 'danger';

export interface SettingsArea {
  id: SettingsAreaId;
  label: string;
  description: string;
  deepLinks: Array<{ label: string; href: string }>;
  danger?: boolean;
}

export interface SettingsSubsection {
  id: string;
  area: SettingsAreaId;
  label: string;
  description: string;
  deepLinkTo?: string;
  advanced?: boolean;
}

export interface SettingsEntry {
  id: string;
  label: string;
  unit?: string;
  default: unknown;
  type: 'number' | 'text' | 'toggle' | 'select' | 'secret' | 'csv';
  options?: Array<{ value: string; label: string }>;
  area: SettingsAreaId;
  subsection: string;
  backendSection: string;
  backendPath: string;
  description: string;
  usedBy: string[];
  deepLinkTo?: string;
  advanced?: boolean;
}

const DATA_ENGINE_EXCHANGE_OPTIONS = [
  { value: 'binance', label: 'Binance' },
  { value: 'bybit', label: 'Bybit' },
  { value: 'okx', label: 'OKX' },
  { value: 'coinbase', label: 'Coinbase' },
  { value: 'kraken', label: 'Kraken' },
];

export const SETTINGS_AREAS: SettingsArea[] = [
  { id: 'home', label: 'Home', description: 'Daily controls, search, and recently changed settings.', deepLinks: [] },
  { id: 'data', label: 'Data', description: 'Local data engine, source priority, coverage, streaming, and retention.', deepLinks: [{ label: 'Data Manager', href: '/data' }] },
  { id: 'lab', label: 'Lab', description: 'Strategy research, pipeline gating, simulation, continuous testing.', deepLinks: [] },
  { id: 'trading', label: 'Trading', description: 'Exchange, mode, capital, risk, regime gating.', deepLinks: [] },
  { id: 'notifications', label: 'Notifications', description: 'Discord transport, event subscriptions, delivery level.', deepLinks: [] },
  { id: 'system', label: 'System', description: 'API keys, remote engine, bot operations, health & telemetry.', deepLinks: [] },
  { id: 'danger', label: 'Danger Zone', description: 'Factory reset, credential purge.', deepLinks: [], danger: true },
];

export const SETTINGS_SUBSECTIONS: SettingsSubsection[] = [
  // Trading
  { id: 'trading-exchange', area: 'trading', label: 'Exchange connection', description: 'Which exchange the bot trades on.', deepLinkTo: '/' },
  { id: 'trading-mode-capital', area: 'trading', label: 'Mode & capital', description: 'Paper vs. live trading and starting equity.' },
  { id: 'trading-credentials-hl', area: 'trading', label: 'Hyperliquid credentials', description: 'Wallet, API address, API secret, and testnet toggle for Hyperliquid.' },
  { id: 'trading-risk-position-sizing', area: 'trading', label: 'Position sizing', description: 'Max position size and max concurrent positions.' },
  { id: 'trading-risk-loss-limits', area: 'trading', label: 'Loss limits', description: 'Daily-loss, drawdown, and cooldown guardrails.', deepLinkTo: '/risk' },
  { id: 'trading-risk-regime-gating', area: 'trading', label: 'Regime gating', description: 'Strict/soft gating of strategies by detected market regime.', deepLinkTo: '/lab' },
  { id: 'trading-risk-advanced', area: 'trading', label: 'Risk advanced', description: 'Rarely-changed risk filter overrides.', advanced: true },

  // Lab
  { id: 'lab-pipeline-quick-screen', area: 'lab', label: 'Quick Screen (Step 1)', description: 'First-pass quick screen thresholds before the gauntlet.' },
  { id: 'lab-pipeline-robustness-gauntlet', area: 'lab', label: 'Robustness Gauntlet (Step 2)', description: 'Robustness, trade count, and Sharpe thresholds for the gauntlet stage.' },
  { id: 'lab-pipeline-paper-live-gates', area: 'lab', label: 'Paper to Live gates', description: 'Gates a paper-trading strategy must clear to graduate to live.' },
  { id: 'lab-pipeline-capacity', area: 'lab', label: 'Pipeline capacity', description: 'WIP caps for unattended strategy promotion lanes.' },
  { id: 'lab-pipeline-live-graduated', area: 'lab', label: 'Live graduated', description: 'Controls for strategies already running live.' },
  { id: 'lab-pipeline-testing-mode', area: 'lab', label: 'Pipeline testing mode', description: 'Bypass safety gates for end-to-end pipeline testing.', advanced: true },
  { id: 'lab-research', area: 'lab', label: 'Research', description: 'Crucible research cadence and ideation parameters.' },
  { id: 'lab-backtest-defaults', area: 'lab', label: 'Gauntlet defaults', description: 'Symbol, timeframe, fees, slippage, and duration used by ad-hoc Gauntlet runs.' },
  { id: 'lab-walkforward-defaults', area: 'lab', label: 'Walk-forward defaults', description: 'Number of train/test folds and the train ratio used by the walk-forward runner.' },

  // Agents / Models — moved to the dedicated Agents control page (/agents).
  // Both areas now render a redirect card in the Settings shell; their former
  // subsections (AI providers, model policy, personas, scheduler, auxiliary
  // models, backup provider) live as tabs on /agents and have no manifest
  // entries here.

  // Notifications
  { id: 'notif-discord', area: 'notifications', label: 'Discord transport', description: 'Bot token and webhook credentials for Discord.' },
  { id: 'notif-subscriptions', area: 'notifications', label: 'Event subscriptions', description: 'Which events are pushed to Discord.' },
  { id: 'notif-delivery', area: 'notifications', label: 'Delivery policy', description: 'Overall notification level and noise control.' },

  // System
  { id: 'system-api-keys', area: 'system', label: 'Data source API keys', description: 'Tiingo, FRED, CoinGecko, Polygon, Alpaca keys.' },
  { id: 'system-remote-engine', area: 'system', label: 'Remote engine', description: 'Offload backtests to a remote engine process.' },
  { id: 'system-throughput', area: 'system', label: 'Throughput', description: 'Agent cadences and pipeline throughput presets.', advanced: true },
  { id: 'system-resource-tuning', area: 'system', label: 'Resource tuning', description: 'Worker counts, claim limits, drain mode, and other backpressure knobs.', advanced: true },
  { id: 'system-telemetry', area: 'system', label: 'Health & telemetry', description: 'Health checks, alert thresholds, and regime detection flags.' },
  { id: 'system-db-maintenance', area: 'system', label: 'Database maintenance', description: 'Retention windows for log/result tables and the optional daily VACUUM job.' },

  // Danger
  { id: 'danger-factory-reset', area: 'danger', label: 'Factory reset', description: 'Wipe databases and credentials to restore a clean slate.' },

  // Data
  { id: 'data-engine-core', area: 'data', label: 'Data Engine', description: 'Opt-in local-first DuckDB engine: enable it, choose exchanges and source priority, point-in-time reads, auto catch-up, on-chain provider, and the source-reconciliation gate.', deepLinkTo: '/data' },
];

export const SETTINGS_MANIFEST: SettingsEntry[] = [
  // -------------------- TRADING --------------------
  // Exchange selection
  {
    id: 'exchange.exchange',
    label: 'Active exchange',
    default: 'hyperliquid',
    type: 'select',
    options: [
      { value: 'hyperliquid', label: 'Hyperliquid' },
    ],
    area: 'trading',
    subsection: 'trading-exchange',
    backendSection: 'exchange',
    backendPath: 'exchange',
    description: 'Which exchange the bot connects to for order placement. Hyperliquid is the only supported live-execution venue.',
    usedBy: ['forven.api_core', 'forven.exchange.hyperliquid'],
    deepLinkTo: '/',
  },

  // Hyperliquid credentials
  {
    id: 'hyperliquid.actual_wallet_address',
    label: 'Hyperliquid wallet address',
    default: '',
    type: 'text',
    area: 'trading',
    subsection: 'trading-credentials-hl',
    backendSection: 'hyperliquid',
    backendPath: 'hyperliquid_wallet',
    description: 'On-chain wallet address Hyperliquid uses to attribute your orders and balances.',
    usedBy: ['forven.exchange.hyperliquid', 'forven.api_core'],
  },
  {
    id: 'hyperliquid.api_address',
    label: 'Hyperliquid API address',
    default: '',
    type: 'text',
    area: 'trading',
    subsection: 'trading-credentials-hl',
    backendSection: 'hyperliquid',
    backendPath: 'hyperliquid_api_address',
    description: 'Hyperliquid API wallet address (separate from the funding wallet) used to sign requests.',
    usedBy: ['forven.exchange.hyperliquid', 'forven.api_core'],
  },
  {
    id: 'hyperliquid.api_secret_key',
    label: 'Hyperliquid API secret',
    default: '',
    type: 'secret',
    area: 'trading',
    subsection: 'trading-credentials-hl',
    backendSection: 'hyperliquid',
    backendPath: 'api_secret_key',
    description: 'Private key Hyperliquid uses to sign API requests from this bot.',
    usedBy: ['forven.exchange.hyperliquid', 'forven.api_core'],
  },
  {
    id: 'hyperliquid.use_testnet',
    label: 'Hyperliquid testnet',
    default: true,
    type: 'toggle',
    area: 'trading',
    subsection: 'trading-credentials-hl',
    backendSection: 'hyperliquid',
    backendPath: 'hyperliquid_testnet',
    description: 'Route Hyperliquid orders to testnet so live mode stays paper-safe.',
    usedBy: ['forven.exchange.hyperliquid', 'forven.api_core'],
  },

  // Mode & capital
  {
    id: 'trading-mode.trading_mode',
    label: 'Trading mode',
    default: 'paper',
    type: 'select',
    options: [
      { value: 'paper', label: 'Paper' },
      { value: 'live', label: 'Live' },
    ],
    area: 'trading',
    subsection: 'trading-mode-capital',
    backendSection: 'trading-mode',
    backendPath: 'trading_mode',
    description: 'Whether orders are simulated (paper) or routed to the real exchange (live).',
    usedBy: ['forven.api_core', 'forven.bot', 'forven.runtime_worker'],
  },
  {
    id: 'initial-capital.initial_capital',
    label: 'Initial capital',
    unit: '$',
    default: 10000,
    type: 'number',
    area: 'trading',
    subsection: 'trading-mode-capital',
    backendSection: 'initial-capital',
    backendPath: 'initial_capital',
    description: 'Starting equity used to size positions and compute paper P&L.',
    usedBy: ['forven.api_core', 'forven.bot', 'forven.simulation'],
  },

  // Risk: position sizing
  {
    id: 'risk.max_risk_per_trade_pct',
    label: 'Max risk per trade',
    unit: '%',
    default: 10,
    type: 'number',
    area: 'trading',
    subsection: 'trading-risk-position-sizing',
    backendSection: 'risk',
    backendPath: 'max_risk_per_trade_pct',
    description:
      'Largest share of equity a single trade may put at risk — this is the exact value risk enforcement reads. The legacy max_position_size_pct key is kept in sync automatically on save.',
    usedBy: ['forven.exchange.risk', 'forven.runtime_worker', 'forven.bot'],
  },
  {
    id: 'risk.max_concurrent_positions',
    label: 'Max concurrent positions (live)',
    default: 5,
    type: 'number',
    area: 'trading',
    subsection: 'trading-risk-position-sizing',
    backendSection: 'risk',
    backendPath: 'max_concurrent_positions',
    description:
      'Hard cap on simultaneously open LIVE positions on the shared real wallet. Bounded so the roster can diversify while margin and portfolio-budget limits still apply. 0 = unlimited.',
    usedBy: ['forven.exchange.risk', 'forven.runtime_worker', 'forven.bot'],
  },
  {
    id: 'risk.paper_max_concurrent_positions',
    label: 'Max concurrent positions (paper, per session)',
    default: 0,
    type: 'number',
    area: 'trading',
    subsection: 'trading-risk-position-sizing',
    backendSection: 'risk',
    backendPath: 'paper_max_concurrent_positions',
    description:
      'Cap on open positions PER paper session (each strategy is an isolated sandbox, so sessions never block each other). 0 = unlimited.',
    usedBy: ['forven.exchange.risk'],
  },
  {
    id: 'risk.live_books_enabled',
    label: 'Live direction books (long/short sub-accounts)',
    default: false,
    type: 'toggle',
    area: 'trading',
    subsection: 'trading-risk-position-sizing',
    backendSection: 'risk',
    backendPath: 'live_books_enabled',
    description:
      'Route LIVE longs and shorts to separate Hyperliquid sub-accounts so a long and a short on the same asset can coexist (one account nets them). Requires the book addresses below. Paper is unaffected.',
    usedBy: ['forven.exchange.books', 'forven.scanner', 'forven.exchange.risk'],
  },
  {
    id: 'risk.hyperliquid_long_book_address',
    label: 'Long-book sub-account address',
    default: '',
    type: 'text',
    area: 'trading',
    subsection: 'trading-risk-position-sizing',
    backendSection: 'risk',
    backendPath: 'hyperliquid_long_book_address',
    description:
      'Hyperliquid sub-account address that holds LIVE long exposure. Leave blank to use the master wallet for longs.',
    usedBy: ['forven.exchange.books', 'forven.scanner'],
  },
  {
    id: 'risk.hyperliquid_short_book_address',
    label: 'Short-book sub-account address',
    default: '',
    type: 'text',
    area: 'trading',
    subsection: 'trading-risk-position-sizing',
    backendSection: 'risk',
    backendPath: 'hyperliquid_short_book_address',
    description:
      'Hyperliquid sub-account address that holds LIVE short exposure. While blank, the system runs LONG ONLY — short signals are skipped with a warning until a short sub-account is configured (a fresh mainnet wallet may need $100k cumulative volume to create a 2nd sub-account).',
    usedBy: ['forven.exchange.books', 'forven.scanner'],
  },
  {
    id: 'risk.hyperliquid_use_cross_margin',
    label: 'Use cross margin (live)',
    default: false,
    type: 'toggle',
    area: 'trading',
    subsection: 'trading-risk-position-sizing',
    backendSection: 'risk',
    backendPath: 'hyperliquid_use_cross_margin',
    description:
      'OFF (default) = ISOLATED margin: each live position loss is capped at its own margin at the leverage the bot sets per trade. ON = cross margin (the whole sub-account backs every position). Isolated is safer and matches the per-trade risk model. The bot sets leverage + this mode on the exchange before every live entry.',
    usedBy: ['forven.exchange.hyperliquid'],
  },
  {
    id: 'risk.liq_distance_warn_pct',
    label: 'Liquidation-distance warning',
    unit: '%',
    default: 15,
    type: 'number',
    area: 'trading',
    subsection: 'trading-risk-position-sizing',
    backendSection: 'risk',
    backendPath: 'liq_distance_warn_pct',
    description:
      'Alert (warning) when an open LIVE position is within this % of its liquidation price. The daemon checks every open position each tick.',
    usedBy: ['forven.daemon'],
  },
  {
    id: 'risk.liq_distance_critical_pct',
    label: 'Liquidation-distance critical',
    unit: '%',
    default: 7,
    type: 'number',
    area: 'trading',
    subsection: 'trading-risk-position-sizing',
    backendSection: 'risk',
    backendPath: 'liq_distance_critical_pct',
    description:
      'Critical alert when an open LIVE position is within this % of its liquidation price — reduce or add margin.',
    usedBy: ['forven.daemon'],
  },

  // Risk: loss limits
  {
    id: 'risk.max_daily_loss_pct',
    label: 'Max daily loss',
    unit: '%',
    default: 2,
    type: 'number',
    area: 'trading',
    subsection: 'trading-risk-loss-limits',
    backendSection: 'risk',
    backendPath: 'max_daily_loss_pct',
    description:
      'Share of equity lost in a day (realized plus unrealized) before new entries are blocked — this percent is the exact value risk enforcement reads. The legacy USD twin (max_daily_loss) is derived from initial capital on save.',
    usedBy: ['forven.exchange.risk', 'forven.runtime_worker', 'forven.monitoring'],
    deepLinkTo: '/risk',
  },
  {
    id: 'risk.max_drawdown_pct',
    label: 'Max drawdown',
    unit: '%',
    default: 30,
    type: 'number',
    area: 'trading',
    subsection: 'trading-risk-loss-limits',
    backendSection: 'risk',
    backendPath: 'max_drawdown_pct',
    description:
      'Peak-to-trough equity drawdown that triggers the kill switch. Enforcement clamps this to the 1–30% range.',
    usedBy: ['forven.exchange.risk', 'forven.runtime_worker', 'forven.monitoring'],
    deepLinkTo: '/risk',
  },
  {
    id: 'risk.cooldown_after_loss_hours',
    label: 'Cooldown after loss',
    unit: 'hours',
    default: 0,
    type: 'number',
    area: 'trading',
    subsection: 'trading-risk-loss-limits',
    backendSection: 'risk',
    backendPath: 'cooldown_after_loss_hours',
    description: 'Pause before a new entry is permitted after a losing trade closes.',
    usedBy: ['forven.exchange.risk', 'forven.runtime_worker'],
  },

  // Risk: regime gating (deduped — ONLY under trading, not health)
  {
    id: 'risk.strict_regime_gating',
    label: 'Strict regime gating',
    default: true,
    type: 'toggle',
    area: 'trading',
    subsection: 'trading-risk-regime-gating',
    backendSection: 'risk',
    backendPath: 'strict_regime_gating',
    description: 'Block trades when the strategy/regime compatibility check fails.',
    usedBy: ['forven.runtime_worker', 'forven.policy', 'forven.routers.system'],
    deepLinkTo: '/lab',
  },
  {
    id: 'risk.regime_min_confidence',
    label: 'Regime minimum confidence',
    default: 0.3,
    type: 'number',
    area: 'trading',
    subsection: 'trading-risk-regime-gating',
    backendSection: 'risk',
    backendPath: 'regime_min_confidence',
    description: 'Minimum regime-classifier confidence required before gating decisions are enforced.',
    usedBy: ['forven.runtime_worker', 'forven.policy'],
    deepLinkTo: '/lab',
  },
  {
    id: 'risk.allow_unknown_regime_strategies',
    label: 'Allow unknown strategy types',
    default: false,
    type: 'toggle',
    area: 'trading',
    subsection: 'trading-risk-regime-gating',
    backendSection: 'risk',
    backendPath: 'allow_unknown_regime_strategies',
    description: 'Let strategies whose regime affinity is unclassified pass the regime gate.',
    usedBy: ['forven.runtime_worker', 'forven.policy'],
    deepLinkTo: '/lab',
  },

  // Risk: advanced
  {
    id: 'risk.relaxed_trade_filters_enabled',
    label: 'Relaxed testing mode',
    default: false,
    type: 'toggle',
    area: 'trading',
    subsection: 'trading-risk-advanced',
    backendSection: 'risk',
    backendPath: 'relaxed_trade_filters_enabled',
    description: 'Bypass sentiment and regime gates for testing — use only when validating plumbing.',
    usedBy: ['forven.runtime_worker', 'forven.policy'],
    advanced: true,
  },

  // -------------------- LAB: PIPELINE --------------------
  // Pipeline testing mode (via updatePipelineSettings / pipelineConfig)
  {
    id: 'pipeline.testing_mode',
    label: 'Pipeline testing mode',
    default: false,
    type: 'toggle',
    area: 'lab',
    subsection: 'lab-pipeline-testing-mode',
    backendSection: 'pipeline',
    backendPath: 'testing_mode',
    description: 'Bypass safety gates so every strategy flows end-to-end through the pipeline.',
    usedBy: ['forven.strategy_lifecycle', 'forven.routers.strategies'],
    advanced: true,
  },

  // Quick screen (Step 1)
  {
    id: 'pipeline.quick_screen.min_total_return_pct',
    label: 'Quick-screen min total return',
    unit: '%',
    default: 0,
    type: 'number',
    area: 'lab',
    subsection: 'lab-pipeline-quick-screen',
    backendSection: 'pipeline',
    backendPath: 'quick_screen.min_total_return_pct',
    description: 'Minimum cumulative return a strategy must produce to advance past quick screen.',
    usedBy: ['forven.strategy_lifecycle', 'forven.routers.strategies'],
  },
  {
    id: 'pipeline.quick_screen.max_drawdown_pct',
    label: 'Quick-screen max drawdown',
    unit: '%',
    default: 30,
    type: 'number',
    area: 'lab',
    subsection: 'lab-pipeline-quick-screen',
    backendSection: 'pipeline',
    backendPath: 'quick_screen.max_drawdown_pct',
    description: 'Largest drawdown tolerated in quick screen before a strategy is rejected.',
    usedBy: ['forven.strategy_lifecycle', 'forven.routers.strategies'],
  },
  {
    id: 'pipeline.quick_screen.min_sharpe',
    label: 'Quick-screen min Sharpe',
    default: 0.5,
    type: 'number',
    area: 'lab',
    subsection: 'lab-pipeline-quick-screen',
    backendSection: 'pipeline',
    backendPath: 'quick_screen.min_sharpe',
    description: 'Lowest Sharpe a strategy must achieve in quick screen to reach the gauntlet.',
    usedBy: ['forven.strategy_lifecycle', 'forven.routers.strategies'],
  },
  {
    id: 'pipeline.quick_screen.min_profit_factor',
    label: 'Quick-screen min profit factor',
    default: 1.05,
    type: 'number',
    area: 'lab',
    subsection: 'lab-pipeline-quick-screen',
    backendSection: 'pipeline',
    backendPath: 'quick_screen.min_profit_factor',
    description: 'Profit-factor floor enforced at BOTH the in-sample and out-of-sample legs of the quick screen.',
    usedBy: ['forven.policy', 'forven.brain'],
  },
  {
    id: 'pipeline.quick_screen.min_trades',
    label: 'Quick-screen min trades',
    default: 30,
    type: 'number',
    area: 'lab',
    subsection: 'lab-pipeline-quick-screen',
    backendSection: 'pipeline',
    backendPath: 'quick_screen.min_trades',
    description:
      'Minimum in-sample trade count for the quick-screen overfitting guardrails (Gate5). Was a hardcoded 30 before; deferred entirely when testing mode is on.',
    usedBy: ['forven.brain'],
  },
  {
    id: 'pipeline.quick_screen.min_robustness_score',
    label: 'Quick-screen min robustness',
    default: 50,
    type: 'number',
    area: 'lab',
    subsection: 'lab-pipeline-quick-screen',
    backendSection: 'pipeline',
    backendPath: 'quick_screen.min_robustness_score',
    description:
      'Robustness-score floor (0-100) for the quick-screen guardrails (Gate3). The composite score is mostly earned inside the gauntlet, so fresh strategies score near zero — lower this (or enable testing mode) if the pipeline starves at quick screen. Was a hardcoded 50 before.',
    usedBy: ['forven.brain'],
  },
  {
    id: 'pipeline.quick_screen.fitness_min_trades',
    label: 'Fitness scorer min trades',
    default: 20,
    type: 'number',
    area: 'lab',
    subsection: 'lab-pipeline-quick-screen',
    backendSection: 'pipeline',
    backendPath: 'quick_screen.fitness_min_trades',
    description:
      'Trade count at which the fitness scorer awards full marks for sample size. Was a hardcoded 20 before; wired so the fitness curve is tunable.',
    usedBy: ['forven.policy'],
  },
  {
    id: 'pipeline.quick_screen.fitness_min_profit_factor',
    label: 'Fitness scorer min profit factor',
    default: 1.3,
    type: 'number',
    area: 'lab',
    subsection: 'lab-pipeline-quick-screen',
    backendSection: 'pipeline',
    backendPath: 'quick_screen.fitness_min_profit_factor',
    description:
      'Profit-factor reference the fitness scorer scales against (full PF marks at this + 2.0). Was a hardcoded 1.3 before.',
    usedBy: ['forven.policy'],
  },

  // Gauntlet (Step 2)
  {
    id: 'pipeline.gauntlet_auto_quick_screen_enabled',
    label: 'Auto quick screen',
    default: true,
    type: 'toggle',
    area: 'lab',
    subsection: 'lab-pipeline-robustness-gauntlet',
    backendSection: 'pipeline',
    backendPath: 'gauntlet_auto_quick_screen_enabled',
    description: 'Automatically creates a gauntlet workflow for new quick-screen strategy containers.',
    usedBy: ['forven.strategy_lifecycle', 'forven.gauntlet.engine'],
  },
  {
    id: 'risk.allow_unsupported_backtest_risk_controls',
    label: 'Allow stop-dependent promotion',
    default: false,
    type: 'toggle',
    area: 'lab',
    subsection: 'lab-pipeline-robustness-gauntlet',
    backendSection: 'risk',
    backendPath: 'allow_unsupported_backtest_risk_controls',
    description: 'When OFF (default), strategies whose stop-loss/take-profit/sizing the local backtest cannot enforce are blocked from promotion into paper/live. Turn ON only to bypass the parity gate while iterating.',
    usedBy: ['forven.policy'],
  },
  {
    id: 'risk.canonical_requires_forward_proof',
    label: 'Require forward proof for canonical',
    default: false,
    type: 'toggle',
    area: 'lab',
    subsection: 'lab-pipeline-robustness-gauntlet',
    backendSection: 'risk',
    backendPath: 'canonical_requires_forward_proof',
    description: 'When ON, a strategy must reach a forward-traded stage (paper/live) before it earns canonical protection — a gauntlet pass alone is not enough. Tighten this as you approach live.',
    usedBy: ['forven.hypothesis_graduation'],
  },
  {
    id: 'pipeline.gauntlet_step_stale_minutes',
    label: 'Gauntlet stale-step recovery',
    unit: 'min',
    default: 30,
    type: 'number',
    area: 'lab',
    subsection: 'lab-pipeline-robustness-gauntlet',
    backendSection: 'pipeline',
    backendPath: 'gauntlet_step_stale_minutes',
    description: 'Minutes before a running gauntlet workflow step is recovered as retryable runtime-blocked after restart.',
    usedBy: ['forven.gauntlet.engine', 'forven.api'],
    advanced: true,
  },
  {
    id: 'pipeline.gate_sweep_timeframes',
    label: 'Gauntlet sweep timeframes',
    default: ['15m', '1h', '4h', '1d'],
    type: 'csv',
    options: [
      { value: '5m', label: '5m' },
      { value: '15m', label: '15m' },
      { value: '30m', label: '30m' },
      { value: '1h', label: '1h' },
      { value: '4h', label: '4h' },
      { value: '1d', label: '1d' },
    ],
    area: 'lab',
    subsection: 'lab-pipeline-robustness-gauntlet',
    backendSection: 'pipeline',
    backendPath: 'gate_sweep_timeframes',
    description: 'Timeframes used for the multi-timeframe sweep before validation optimization.',
    usedBy: ['forven.gauntlet.tasks', 'forven.routers.lifecycle'],
  },
  {
    id: 'pipeline.gauntlet.min_robustness_score',
    label: 'Gauntlet min robustness score',
    default: 50,
    type: 'number',
    area: 'lab',
    subsection: 'lab-pipeline-robustness-gauntlet',
    backendSection: 'pipeline',
    backendPath: 'gauntlet.min_robustness_score',
    description: 'Composite robustness-score floor required to survive the gauntlet.',
    usedBy: ['forven.strategy_lifecycle', 'forven.routers.robustness'],
  },
  {
    id: 'pipeline.gauntlet.min_trades',
    label: 'Gauntlet min trade count',
    default: 30,
    type: 'number',
    area: 'lab',
    subsection: 'lab-pipeline-robustness-gauntlet',
    backendSection: 'pipeline',
    backendPath: 'gauntlet.min_trades',
    description: 'Minimum closed trades in the gauntlet sample before results are trusted.',
    usedBy: ['forven.strategy_lifecycle', 'forven.routers.robustness'],
  },
  {
    id: 'pipeline.gauntlet.min_sharpe',
    label: 'Gauntlet min Sharpe',
    default: 0.1,
    type: 'number',
    area: 'lab',
    subsection: 'lab-pipeline-robustness-gauntlet',
    backendSection: 'pipeline',
    backendPath: 'gauntlet.min_sharpe',
    description: 'Minimum Sharpe the gauntlet must show for graduation.',
    usedBy: ['forven.strategy_lifecycle', 'forven.routers.robustness'],
  },
  {
    id: 'pipeline.gauntlet.min_oos_profit_factor',
    label: 'Gauntlet min OOS profit factor',
    default: 1.05,
    type: 'number',
    area: 'lab',
    subsection: 'lab-pipeline-robustness-gauntlet',
    backendSection: 'pipeline',
    backendPath: 'gauntlet.min_oos_profit_factor',
    description: 'Out-of-sample profit-factor floor a strategy must clear at the gauntlet gate before paper promotion.',
    usedBy: ['forven.policy', 'forven.strategy_lifecycle'],
  },
  {
    id: 'pipeline.gauntlet.max_drawdown_pct',
    label: 'Gauntlet max drawdown',
    unit: '%',
    default: 30,
    type: 'number',
    area: 'lab',
    subsection: 'lab-pipeline-robustness-gauntlet',
    backendSection: 'pipeline',
    backendPath: 'gauntlet.max_drawdown_pct',
    description: 'Maximum drawdown a gauntlet candidate may incur.',
    usedBy: ['forven.strategy_lifecycle', 'forven.routers.robustness'],
  },
  {
    id: 'pipeline.gauntlet.required_tests',
    label: 'Gauntlet required tests',
    // Mirror the backend's enforced default (DEFAULT_PIPELINE_CONFIG). Checking all five
    // would make monte_carlo and regime_split MANDATORY-present hard gates, newly
    // blocking strategies that lack those artifacts. Those two remain non-required by
    // default; their safety floors (MC tail-drawdown, regime profitability) still fire
    // whenever the test actually ran.
    default: ['walk_forward', 'param_jitter', 'cost_stress'],
    type: 'csv',
    // Canonical test names from forven.policy._GAUNTLET_VALIDATION_TYPES —
    // providing options renders this as checkboxes instead of a free-text CSV.
    options: [
      { value: 'walk_forward', label: 'Walk-forward' },
      { value: 'monte_carlo', label: 'Monte Carlo' },
      { value: 'param_jitter', label: 'Param jitter' },
      { value: 'cost_stress', label: 'Cost stress' },
      { value: 'regime_split', label: 'Regime split' },
    ],
    area: 'lab',
    subsection: 'lab-pipeline-robustness-gauntlet',
    backendSection: 'pipeline',
    backendPath: 'gauntlet.required_tests',
    description: 'Robustness tests that must pass before graduation.',
    usedBy: ['forven.strategy_lifecycle', 'forven.routers.robustness'],
  },
  {
    id: 'pipeline.gauntlet.mc_max_dd_p95',
    label: 'Gauntlet Monte-Carlo p95 max drawdown',
    unit: '%',
    default: 40,
    type: 'number',
    area: 'lab',
    subsection: 'lab-pipeline-robustness-gauntlet',
    backendSection: 'pipeline',
    backendPath: 'gauntlet.mc_max_dd_p95',
    description:
      'Monte-Carlo 95th-percentile drawdown ceiling at the gauntlet->paper gate. SAFETY FLOOR: the paper gate enforces a hard maximum of 40% regardless of this value — you can make it stricter, not looser — and it fires whenever Monte Carlo actually ran.',
    usedBy: ['forven.policy'],
  },
  {
    id: 'pipeline.gauntlet.wfa_min_folds',
    label: 'Walk-forward min folds',
    default: 2,
    type: 'number',
    area: 'lab',
    subsection: 'lab-pipeline-robustness-gauntlet',
    backendSection: 'pipeline',
    backendPath: 'gauntlet.wfa_min_folds',
    description: 'Minimum number of walk-forward folds required at the gauntlet->paper gate.',
    usedBy: ['forven.policy'],
  },
  {
    id: 'pipeline.robustness_thresholds.wfa_fold_pass_rate_min',
    label: 'Walk-forward fold pass-rate floor',
    unit: '%',
    default: 40,
    type: 'number',
    area: 'lab',
    subsection: 'lab-pipeline-robustness-gauntlet',
    backendSection: 'pipeline',
    backendPath: 'robustness_thresholds.wfa_fold_pass_rate_min',
    description:
      'Fraction of walk-forward folds that must be OOS-positive to pass the gauntlet->paper gate. SAFETY FLOOR: the paper gate enforces a hard minimum of 40% (stricter allowed, looser ignored) and it fires whenever walk-forward ran, regardless of the required-tests list.',
    usedBy: ['forven.policy'],
  },
  {
    id: 'pipeline.robustness_thresholds.param_jitter_pass_rate_min',
    label: 'Param-jitter pass-rate floor',
    unit: '%',
    default: 60,
    type: 'number',
    area: 'lab',
    subsection: 'lab-pipeline-robustness-gauntlet',
    backendSection: 'pipeline',
    backendPath: 'robustness_thresholds.param_jitter_pass_rate_min',
    description:
      'Fraction of parameter-jitter perturbations that must stay profitable to pass the gauntlet->paper gate. SAFETY FLOOR: the paper gate enforces a hard minimum of 60% (stricter allowed, looser ignored) and it fires whenever param-jitter ran, regardless of the required-tests list.',
    usedBy: ['forven.policy'],
  },

  // Deflated Sharpe Ratio — optimizer selection-bias guard (observe-then-gate)
  {
    id: 'pipeline.robustness_thresholds.deflated_sharpe_gate_enabled',
    label: 'Deflated Sharpe gate',
    default: false,
    type: 'toggle',
    area: 'lab',
    subsection: 'lab-pipeline-robustness-gauntlet',
    backendSection: 'pipeline',
    backendPath: 'robustness_thresholds.deflated_sharpe_gate_enabled',
    description:
      'When ON, reject strategies whose Deflated Sharpe Ratio (Sharpe corrected for optimizer selection bias / number of trials) is below the minimum. OFF by default — the DSR is always computed and shown on the Robustness tab so you can observe it before enabling the gate.',
    usedBy: ['forven.policy'],
  },
  {
    id: 'pipeline.robustness_thresholds.min_deflated_sharpe',
    label: 'Min Deflated Sharpe',
    default: 0.9,
    type: 'number',
    area: 'lab',
    subsection: 'lab-pipeline-robustness-gauntlet',
    backendSection: 'pipeline',
    backendPath: 'robustness_thresholds.min_deflated_sharpe',
    description:
      'Deflated Sharpe Ratio floor (a probability in 0-1; ~0.95 = conventional significance). Enforced only when the Deflated Sharpe gate is enabled.',
    usedBy: ['forven.policy'],
  },
  // Parameter-jitter compute bounds (the heaviest robustness step: N full-window
  // backtests). These keep the sweep under the step timeout so it can't wedge the
  // gauntlet at param_jitter.
  {
    id: 'pipeline.robustness_thresholds.param_jitter_max_iterations',
    label: 'Param jitter max reruns',
    default: 30,
    type: 'number',
    area: 'lab',
    subsection: 'lab-pipeline-robustness-gauntlet',
    backendSection: 'pipeline',
    backendPath: 'robustness_thresholds.param_jitter_max_iterations',
    description:
      'Hard cap on parameter-jitter reruns regardless of the requested count. Each rerun is a full backtest over the baseline window, so this bounds the total compute and prevents the sweep from overrunning the step timeout.',
    usedBy: ['forven.routers.robustness'],
  },
  {
    id: 'pipeline.robustness_thresholds.param_jitter_max_bars',
    label: 'Param jitter window cap',
    unit: 'bars',
    default: 4380,
    type: 'number',
    area: 'lab',
    subsection: 'lab-pipeline-robustness-gauntlet',
    backendSection: 'pipeline',
    backendPath: 'robustness_thresholds.param_jitter_max_bars',
    description:
      'Per-rerun bar cap for parameter-jitter reruns (~4380 = 6 months at 1h). Smaller than the other tests because jitter runs many reruns; still wide enough to capture the baseline trades. Lower it if param_jitter is slow; raise it for more window coverage.',
    usedBy: ['forven.routers.robustness'],
  },
  {
    id: 'pipeline.robustness_thresholds.param_jitter_deadline_seconds',
    label: 'Param jitter deadline',
    unit: 'seconds',
    default: 240,
    type: 'number',
    area: 'lab',
    subsection: 'lab-pipeline-robustness-gauntlet',
    backendSection: 'pipeline',
    backendPath: 'robustness_thresholds.param_jitter_deadline_seconds',
    description:
      'Wall-clock safety net for the parameter-jitter sweep. Once exceeded (and at least one rerun has completed), the verdict is computed from the completed reruns instead of overrunning the step timeout. Set 0 to disable.',
    usedBy: ['forven.routers.robustness'],
  },
  {
    id: 'pipeline.gauntlet.async_result_max_age_minutes',
    label: 'Async result max age',
    unit: 'minutes',
    default: 60,
    type: 'number',
    area: 'lab',
    subsection: 'lab-pipeline-robustness-gauntlet',
    backendSection: 'pipeline',
    backendPath: 'gauntlet.async_result_max_age_minutes',
    description:
      'How long a gauntlet async result (e.g. an optimization job) may stay "running" before the step treats it as a zombie and re-submits. Prevents a stuck poll from wedging the workflow forever (the step heartbeat otherwise hides it from stale-step recovery).',
    usedBy: ['forven.gauntlet.tasks'],
  },
  {
    id: 'pipeline.gauntlet.gauntlet_enforce_win_rate',
    label: 'Enforce win-rate gate',
    default: false,
    type: 'toggle',
    area: 'lab',
    subsection: 'lab-pipeline-robustness-gauntlet',
    backendSection: 'pipeline',
    backendPath: 'gauntlet.gauntlet_enforce_win_rate',
    description:
      'OFF by default: win-rate is not a quality signal (momentum/breakout strategies win ~30-40% and profit on payoff ratio), so a win-rate floor auto-rejects a legitimate family. Profit factor / OOS edge screen instead. Turn on only if you specifically want a win-rate floor.',
    usedBy: ['forven.policy'],
  },
  {
    id: 'pipeline.robustness_thresholds.cost_stress_max_degradation_pct',
    label: 'Cost-stress max degradation',
    unit: '%',
    default: 60,
    type: 'number',
    area: 'lab',
    subsection: 'lab-pipeline-robustness-gauntlet',
    backendSection: 'pipeline',
    backendPath: 'robustness_thresholds.cost_stress_max_degradation_pct',
    description:
      'Max Sharpe degradation under 2x fees/slippage allowed at the paper->live gate. The edge must SURVIVE higher costs proportionally, not merely clear an absolute floor. Strict-live only.',
    usedBy: ['forven.policy'],
  },
  {
    id: 'pipeline.paper_trading.live_strict_robustness_enabled',
    label: 'Strict-live robustness battery',
    default: true,
    type: 'toggle',
    area: 'lab',
    subsection: 'lab-pipeline-paper-live-gates',
    backendSection: 'pipeline',
    backendPath: 'paper_trading.live_strict_robustness_enabled',
    description:
      'ON by default ("strict live"): enforce the full robustness battery (walk-forward degradation / absolute OOS Sharpe / OOS trades, Monte-Carlo percentile, cost-stress survival, regime consistency) at the paper->live capital gate. These are demoted to advisory at the gauntlet->paper gate ("achievable paper").',
    usedBy: ['forven.policy'],
  },
  {
    id: 'pipeline.robustness_thresholds.wfa_min_fold_trades',
    label: 'Walk-forward min fold trades',
    unit: 'trades',
    default: 5,
    type: 'number',
    area: 'lab',
    subsection: 'lab-pipeline-robustness-gauntlet',
    backendSection: 'pipeline',
    backendPath: 'robustness_thresholds.wfa_min_fold_trades',
    description:
      'Minimum OOS trades a walk-forward fold must have to count toward the fold pass-rate. Near-empty folds (e.g. a trend system sitting out a flat window) are excluded from both numerator and denominator so they cannot drag the pass-rate into a false reject.',
    usedBy: ['forven.policy'],
  },

  // Paper trading gates
  {
    id: 'pipeline.paper_trading.min_paper_days',
    label: 'Paper min duration',
    unit: 'days',
    default: 14,
    type: 'number',
    area: 'lab',
    subsection: 'lab-pipeline-paper-live-gates',
    backendSection: 'pipeline',
    backendPath: 'paper_trading.min_paper_days',
    description: 'Minimum days a strategy must run in paper before it can promote to live.',
    usedBy: ['forven.strategy_lifecycle', 'forven.api_domains.paper'],
  },
  {
    id: 'pipeline.paper_trading.min_closed_trades',
    label: 'Paper min closed trades',
    default: 50,
    type: 'number',
    area: 'lab',
    subsection: 'lab-pipeline-paper-live-gates',
    backendSection: 'pipeline',
    backendPath: 'paper_trading.min_closed_trades',
    description: 'Closed paper trades required before a graduation decision.',
    usedBy: ['forven.strategy_lifecycle', 'forven.api_domains.paper'],
  },
  {
    id: 'pipeline.paper_trading.min_total_return_pct',
    label: 'Paper min total return',
    unit: '%',
    // TODO confirm default
    default: 0,
    type: 'number',
    area: 'lab',
    subsection: 'lab-pipeline-paper-live-gates',
    backendSection: 'pipeline',
    backendPath: 'paper_trading.min_total_return_pct',
    description: 'Minimum cumulative paper return before promotion is allowed.',
    usedBy: ['forven.strategy_lifecycle', 'forven.api_domains.paper'],
  },
  {
    id: 'pipeline.paper_trading.max_drawdown_pct',
    label: 'Paper max drawdown',
    unit: '%',
    default: 15,
    type: 'number',
    area: 'lab',
    subsection: 'lab-pipeline-paper-live-gates',
    backendSection: 'pipeline',
    backendPath: 'paper_trading.max_drawdown_pct',
    description: 'Drawdown ceiling during paper trading — exceeding it blocks promotion.',
    usedBy: ['forven.strategy_lifecycle', 'forven.api_domains.paper'],
  },
  {
    id: 'pipeline.paper_trading.min_profit_factor_live',
    label: 'Live min profit factor',
    default: 1.5,
    type: 'number',
    area: 'lab',
    subsection: 'lab-pipeline-paper-live-gates',
    backendSection: 'pipeline',
    backendPath: 'paper_trading.min_profit_factor_live',
    description: 'Hard profit-factor floor (OOS preferred) a paper strategy must clear to graduate to live capital.',
    usedBy: ['forven.policy', 'forven.strategy_lifecycle'],
  },
  {
    id: 'pipeline.paper_trading.min_paper_sharpe',
    label: 'Paper min forward Sharpe',
    default: 1,
    type: 'number',
    area: 'lab',
    subsection: 'lab-pipeline-paper-live-gates',
    backendSection: 'pipeline',
    backendPath: 'paper_trading.min_paper_sharpe',
    description:
      'Forward-paper Sharpe (per-trade t-stat) the actual paper trades must show before live graduation — proves real forward edge, not just a positive return. Skipped for a zero-variance series. Set 0 to disable; raise toward ~1.6-2.0 before enabling real-money graduation.',
    usedBy: ['forven.policy'],
  },
  {
    id: 'pipeline.paper_trading.min_profit_factor_paper',
    label: 'Paper min forward profit factor',
    default: 1.2,
    type: 'number',
    area: 'lab',
    subsection: 'lab-pipeline-paper-live-gates',
    backendSection: 'pipeline',
    backendPath: 'paper_trading.min_profit_factor_paper',
    description:
      'Profit factor the actual forward paper trades must show before live graduation (distinct from the historical/backtest PF floor). Set 0 to disable.',
    usedBy: ['forven.policy'],
  },
  {
    id: 'pipeline.paper_trading.pf_position_reduction_threshold',
    label: 'PF half-size threshold',
    default: 2,
    type: 'number',
    area: 'lab',
    subsection: 'lab-pipeline-paper-live-gates',
    backendSection: 'pipeline',
    backendPath: 'paper_trading.pf_position_reduction_threshold',
    description: 'Profit factor below this (but above the live floor) still graduates, at 50% position sizing.',
    usedBy: ['forven.policy', 'forven.strategy_lifecycle'],
  },
  {
    id: 'pipeline.paper_trading.max_oos_is_ratio',
    label: 'Max OOS/IS Sharpe ratio',
    unit: 'x',
    default: 1.5,
    type: 'number',
    area: 'lab',
    subsection: 'lab-pipeline-paper-live-gates',
    backendSection: 'pipeline',
    backendPath: 'paper_trading.max_oos_is_ratio',
    description: 'Blocks live graduation when OOS Sharpe exceeds IS Sharpe by more than this ratio (a lucky/overfit OOS window).',
    usedBy: ['forven.policy', 'forven.strategy_lifecycle'],
  },

  // Pipeline capacity
  {
    id: 'pipeline.paper_wip_cap_mode',
    label: 'Paper lane capacity mode',
    default: 'capped',
    type: 'select',
    options: [
      { value: 'unlimited', label: 'Unlimited' },
      { value: 'capped', label: 'Capped' },
    ],
    area: 'lab',
    subsection: 'lab-pipeline-capacity',
    backendSection: 'pipeline',
    backendPath: 'paper_wip_cap_mode',
    description: 'Controls whether gauntlet winners can always enter paper, or stop at a fixed active paper count.',
    usedBy: ['forven.lab_features', 'forven.strategy_lifecycle'],
  },
  {
    id: 'pipeline.paper_wip_cap',
    label: 'Paper strategy cap',
    default: 20,
    type: 'number',
    area: 'lab',
    subsection: 'lab-pipeline-capacity',
    backendSection: 'pipeline',
    backendPath: 'paper_wip_cap',
    description: 'Maximum active paper strategies when the paper lane is capped. Ignored while capacity mode is unlimited.',
    usedBy: ['forven.lab_features', 'forven.strategy_lifecycle'],
  },
  {
    id: 'pipeline.graveyard_strategy_limit_mode',
    label: 'Graveyard load mode',
    default: 'capped',
    type: 'select',
    options: [
      { value: 'unlimited', label: 'Unlimited' },
      { value: 'capped', label: 'Capped' },
    ],
    area: 'lab',
    subsection: 'lab-pipeline-capacity',
    backendSection: 'pipeline',
    backendPath: 'graveyard_strategy_limit_mode',
    description: 'Controls whether the Lab Manager loads every graveyard strategy or stops at a configured count.',
    usedBy: ['forven.routers.strategies', 'frontend.routes.lab'],
  },
  {
    id: 'pipeline.graveyard_strategy_limit',
    label: 'Graveyard strategy cap',
    default: 500,
    type: 'number',
    area: 'lab',
    subsection: 'lab-pipeline-capacity',
    backendSection: 'pipeline',
    backendPath: 'graveyard_strategy_limit',
    description: 'Maximum graveyard strategies loaded when graveyard load mode is capped. Ignored when mode is unlimited.',
    usedBy: ['forven.routers.strategies', 'frontend.routes.lab'],
  },

  // Live graduated
  {
    id: 'pipeline.live_graduated.decay_kill_switch_pct',
    label: 'Live decay kill switch',
    unit: '%',
    default: 30,
    type: 'number',
    area: 'lab',
    subsection: 'lab-pipeline-live-graduated',
    backendSection: 'pipeline',
    backendPath: 'live_graduated.decay_kill_switch_pct',
    description: 'Performance-decay threshold that automatically retires a live strategy.',
    usedBy: ['forven.strategy_lifecycle', 'forven.health_monitor'],
  },

  // Research (delegated to ResearchSettingsPanel — persisted via saveSection('research', {research_settings: ...}))
  {
    id: 'research.research_settings',
    label: 'Research settings',
    default: {},
    type: 'text',
    area: 'lab',
    subsection: 'lab-research',
    backendSection: 'research',
    backendPath: 'research_settings',
    description: 'Crucible cadence, ideation sources, and other research-panel configuration.',
    usedBy: ['forven.api_core', 'forven.agents.tools_research', 'forven.api_domains.hypotheses'],
  },

  // -------------------- LAB: BACKTEST DEFAULTS --------------------
  {
    id: 'backtesting-defaults.backtest_symbol',
    label: 'Gauntlet default symbol',
    default: 'BTC/USDT',
    type: 'text',
    area: 'lab',
    subsection: 'lab-backtest-defaults',
    backendSection: 'backtesting-defaults',
    backendPath: 'backtest_symbol',
    description: 'Symbol used by ad-hoc Gauntlet runs when none is specified.',
    usedBy: ['forven.api_core', 'forven.routers.backtesting', 'forven.strategies.backtest'],
  },
  {
    id: 'backtesting-defaults.backtest_timeframe',
    label: 'Gauntlet default timeframe',
    default: '1h',
    type: 'select',
    options: [
      { value: '1m', label: '1 minute' },
      { value: '5m', label: '5 minutes' },
      { value: '15m', label: '15 minutes' },
      { value: '30m', label: '30 minutes' },
      { value: '1h', label: '1 hour' },
      { value: '4h', label: '4 hours' },
      { value: '1d', label: '1 day' },
    ],
    area: 'lab',
    subsection: 'lab-backtest-defaults',
    backendSection: 'backtesting-defaults',
    backendPath: 'backtest_timeframe',
    description: 'Candle timeframe used by ad-hoc Gauntlet runs when none is specified.',
    usedBy: ['forven.api_core', 'forven.routers.backtesting', 'forven.strategies.backtest'],
  },
  {
    id: 'backtesting-defaults.backtest_duration_days',
    label: 'Gauntlet duration',
    unit: 'days',
    default: 365,
    type: 'number',
    area: 'lab',
    subsection: 'lab-backtest-defaults',
    backendSection: 'backtesting-defaults',
    backendPath: 'backtest_duration_days',
    description: 'Default window (in days) loaded for ad-hoc Gauntlet runs.',
    usedBy: ['forven.api_core', 'forven.routers.backtesting', 'forven.strategies.backtest'],
  },
  {
    id: 'backtesting-defaults.rolling_backtest_days',
    label: 'Rolling Gauntlet duration',
    unit: 'days',
    default: 30,
    type: 'number',
    area: 'lab',
    subsection: 'lab-backtest-defaults',
    backendSection: 'backtesting-defaults',
    backendPath: 'rolling_backtest_days',
    description: 'Window size used by continuous rolling health Gauntlet runs.',
    usedBy: ['forven.api_core', 'forven.health_monitor'],
  },
  {
    id: 'backtesting-defaults.backtest_fee_bps',
    label: 'Gauntlet fee',
    unit: 'bps',
    default: 4.5,
    type: 'number',
    area: 'lab',
    subsection: 'lab-backtest-defaults',
    backendSection: 'backtesting-defaults',
    backendPath: 'backtest_fee_bps',
    description: 'Per-side fee (in basis points) applied to simulated fills.',
    usedBy: ['forven.api_core', 'forven.strategies.backtest', 'forven.simulation'],
  },
  {
    id: 'backtesting-defaults.backtest_slippage_bps',
    label: 'Gauntlet slippage',
    unit: 'bps',
    default: 2.0,
    type: 'number',
    area: 'lab',
    subsection: 'lab-backtest-defaults',
    backendSection: 'backtesting-defaults',
    backendPath: 'backtest_slippage_bps',
    description: 'Slippage (in basis points) applied to simulated fills.',
    usedBy: ['forven.api_core', 'forven.strategies.backtest', 'forven.simulation'],
  },
  {
    id: 'backtesting-defaults.backtest_include_funding',
    label: 'Include funding costs',
    default: true,
    type: 'toggle',
    area: 'lab',
    subsection: 'lab-backtest-defaults',
    backendSection: 'backtesting-defaults',
    backendPath: 'backtest_include_funding',
    description: 'Deduct cumulative perp funding from simulated PnL and hold strategies with incomplete funding data out of promotion.',
    usedBy: ['forven.api_core', 'forven.strategies.backtest', 'forven.policy'],
  },

  // Walk-forward defaults (saved via same 'backtesting-defaults' section)
  {
    id: 'backtesting-defaults.walkforward_folds',
    label: 'Walk-forward folds',
    default: 5,
    type: 'number',
    area: 'lab',
    subsection: 'lab-walkforward-defaults',
    backendSection: 'backtesting-defaults',
    backendPath: 'walkforward_folds',
    description: 'Number of train/test folds used by the walk-forward runner.',
    usedBy: ['forven.api_core', 'forven.routers.backtesting'],
  },
  {
    id: 'backtesting-defaults.walkforward_train_ratio',
    label: 'Walk-forward train ratio',
    default: 0.7,
    type: 'number',
    area: 'lab',
    subsection: 'lab-walkforward-defaults',
    backendSection: 'backtesting-defaults',
    backendPath: 'walkforward_train_ratio',
    description: 'Fraction of each fold used for training (remainder is test).',
    usedBy: ['forven.api_core', 'forven.routers.backtesting'],
  },

  // -------------------- AGENTS --------------------
  // Model policy (agent_model_keys), personas, per-agent documents, and
  // scheduler jobs are roster-keyed and rendered by SettingsAgents.svelte
  // against /forven/agents, /forven/agents/model-options, and
  // /forven/scheduler — NOT via this flat manifest.

  // -------------------- NOTIFICATIONS --------------------
  {
    id: 'notifications.discord_bot_token',
    label: 'Discord bot token',
    default: '',
    type: 'secret',
    area: 'notifications',
    subsection: 'notif-discord',
    backendSection: 'notifications',
    backendPath: 'discord_bot_token',
    description: 'Main Discord bot token used by the brain to post notifications.',
    usedBy: ['forven.api_core', 'forven.bot'],
  },
  {
    id: 'notifications.discord_webhook_url',
    label: 'Discord webhook URL',
    default: '',
    type: 'secret',
    area: 'notifications',
    subsection: 'notif-discord',
    backendSection: 'notifications',
    backendPath: 'discord_webhook_url',
    description: 'Webhook URL that receives notifications when no bot is connected.',
    usedBy: ['forven.api_core', 'forven.bot'],
  },
  {
    id: 'notifications.notification_level',
    label: 'Notification level',
    default: 'all',
    type: 'select',
    options: [
      { value: 'all', label: 'All' },
      { value: 'none', label: 'Off' },
    ],
    area: 'notifications',
    subsection: 'notif-delivery',
    backendSection: 'notifications',
    backendPath: 'notification_level',
    description: 'Coarse delivery policy that suppresses or enables channels of notifications.',
    usedBy: ['forven.api_core', 'forven.bot'],
  },
  {
    id: 'notifications.notify_on_entry',
    label: 'Notify on trade entry',
    default: true,
    type: 'toggle',
    area: 'notifications',
    subsection: 'notif-subscriptions',
    backendSection: 'notifications',
    backendPath: 'notify_on_entry',
    description: 'Send a notification when a new position opens.',
    usedBy: ['forven.api_core', 'forven.bot'],
  },
  {
    id: 'notifications.notify_on_exit',
    label: 'Notify on trade exit',
    default: true,
    type: 'toggle',
    area: 'notifications',
    subsection: 'notif-subscriptions',
    backendSection: 'notifications',
    backendPath: 'notify_on_exit',
    description: 'Send a notification when a position closes.',
    usedBy: ['forven.api_core', 'forven.bot'],
  },
  {
    id: 'notifications.notify_daily_summary',
    label: 'Daily P&L summary',
    default: true,
    type: 'toggle',
    area: 'notifications',
    subsection: 'notif-subscriptions',
    backendSection: 'notifications',
    backendPath: 'notify_daily_summary',
    description: 'Send a once-per-day P&L and activity digest.',
    usedBy: ['forven.api_core', 'forven.bot'],
  },
  {
    id: 'notifications.notify_health_reports',
    label: 'Health reports',
    default: true,
    type: 'toggle',
    area: 'notifications',
    subsection: 'notif-subscriptions',
    backendSection: 'notifications',
    backendPath: 'notify_health_reports',
    description: 'Send strategy health and degradation reports.',
    usedBy: ['forven.api_core', 'forven.health_monitor'],
  },
  {
    id: 'notifications.notify_errors',
    label: 'Errors & warnings',
    default: true,
    type: 'toggle',
    area: 'notifications',
    subsection: 'notif-subscriptions',
    backendSection: 'notifications',
    backendPath: 'notify_errors',
    description: 'Forward runtime errors and warnings to the notification channel.',
    usedBy: ['forven.api_core', 'forven.bot'],
  },

  // -------------------- SYSTEM: BOT OPERATIONS --------------------

  // Throughput (advanced)
  {
    id: 'bot-operations.scanner_execution_enabled',
    label: 'Scanner execution enabled',
    default: true,
    type: 'toggle',
    area: 'system',
    subsection: 'system-throughput',
    backendSection: 'bot-operations',
    backendPath: 'scanner_execution_enabled',
    description: 'Allow the scanner loop to place live orders when signals fire.',
    usedBy: ['forven.scanner', 'forven.runtime_worker'],
    advanced: true,
  },
  {
    id: 'bot-operations.execution_fast_path_enabled',
    label: 'Execution fast path',
    default: true,
    type: 'toggle',
    area: 'system',
    subsection: 'system-throughput',
    backendSection: 'bot-operations',
    backendPath: 'execution_fast_path_enabled',
    description: 'Skip the slow in-process brain path and execute signals synchronously.',
    usedBy: ['forven.runtime_worker', 'forven.scanner'],
    advanced: true,
  },
  {
    id: 'bot-operations.throughput_auto_scheduler_control',
    label: 'Auto scheduler control',
    default: true,
    type: 'toggle',
    area: 'system',
    subsection: 'system-throughput',
    backendSection: 'bot-operations',
    backendPath: 'throughput_auto_scheduler_control',
    description: 'Let the throughput manager adjust scheduler cadences automatically.',
    usedBy: ['forven.scheduler', 'forven.control_plane.ops'],
    advanced: true,
  },
  {
    id: 'bot-operations.adaptive_pipeline_throughput_enabled',
    label: 'Adaptive pipeline throughput',
    default: false,
    type: 'toggle',
    area: 'system',
    subsection: 'system-throughput',
    backendSection: 'bot-operations',
    backendPath: 'adaptive_pipeline_throughput_enabled',
    description: 'Scale pipeline throughput up or down based on saturation signals.',
    usedBy: ['forven.strategy_lifecycle', 'forven.control_plane.ops'],
    advanced: true,
  },
  {
    id: 'bot-operations.pipeline_target_clear_hours',
    label: 'Pipeline target clear',
    unit: 'hours',
    default: 6,
    type: 'number',
    area: 'system',
    subsection: 'system-throughput',
    backendSection: 'bot-operations',
    backendPath: 'pipeline_target_clear_hours',
    description: 'How quickly the adaptive controller aims to drain the pipeline backlog.',
    usedBy: ['forven.strategy_lifecycle', 'forven.control_plane.ops'],
    advanced: true,
  },
  {
    id: 'bot-operations.ideation_interval_minutes',
    label: 'Ideation interval',
    unit: 'minutes',
    default: 15,
    type: 'number',
    area: 'system',
    subsection: 'system-throughput',
    backendSection: 'bot-operations',
    backendPath: 'ideation_interval_minutes',
    description: 'Minutes between ideation agent runs.',
    usedBy: ['forven.scheduler', 'forven.agents.runner'],
    advanced: true,
  },
  {
    id: 'bot-operations.coding_interval_minutes',
    label: 'Coding interval',
    unit: 'minutes',
    default: 15,
    type: 'number',
    area: 'system',
    subsection: 'system-throughput',
    backendSection: 'bot-operations',
    backendPath: 'coding_interval_minutes',
    description: 'Minutes between coding-agent runs that produce new strategy code.',
    usedBy: ['forven.scheduler', 'forven.agents.runner'],
    advanced: true,
  },
  {
    id: 'bot-operations.testing_interval_minutes',
    label: 'Testing interval',
    unit: 'minutes',
    default: 15,
    type: 'number',
    area: 'system',
    subsection: 'system-throughput',
    backendSection: 'bot-operations',
    backendPath: 'testing_interval_minutes',
    description: 'Minutes between testing-agent passes.',
    usedBy: ['forven.scheduler', 'forven.agents.runner'],
    advanced: true,
  },
  {
    id: 'bot-operations.graduation_interval_minutes',
    label: 'Graduation interval',
    unit: 'minutes',
    default: 120,
    type: 'number',
    area: 'system',
    subsection: 'system-throughput',
    backendSection: 'bot-operations',
    backendPath: 'graduation_interval_minutes',
    description: 'Minutes between graduation-agent evaluations of candidate strategies.',
    usedBy: ['forven.scheduler', 'forven.strategy_lifecycle'],
    advanced: true,
  },

  // Resource tuning (advanced)
  {
    id: 'bot-operations.backtest_matrix_workers',
    label: 'Gauntlet matrix workers',
    default: 4,
    type: 'number',
    area: 'system',
    subsection: 'system-resource-tuning',
    backendSection: 'bot-operations',
    backendPath: 'backtest_matrix_workers',
    description: 'Worker count used by the backtest matrix runner.',
    usedBy: ['forven.strategies.backtest', 'forven.runtime_worker'],
    advanced: true,
  },
  {
    id: 'bot-operations.pipeline_saturation_threshold',
    label: 'Pipeline saturation threshold',
    default: 100,
    type: 'number',
    area: 'system',
    subsection: 'system-resource-tuning',
    backendSection: 'bot-operations',
    backendPath: 'pipeline_saturation_threshold',
    description: 'Queue depth at which adaptive throughput begins throttling new work.',
    usedBy: ['forven.strategy_lifecycle', 'forven.control_plane.ops'],
    advanced: true,
  },
  {
    id: 'bot-operations.pipeline_resume_threshold',
    label: 'Pipeline resume threshold',
    default: 60,
    type: 'number',
    area: 'system',
    subsection: 'system-resource-tuning',
    backendSection: 'bot-operations',
    backendPath: 'pipeline_resume_threshold',
    description: 'Queue depth at which throttling is released and new work resumes.',
    usedBy: ['forven.strategy_lifecycle', 'forven.control_plane.ops'],
    advanced: true,
  },
  {
    id: 'bot-operations.scanner_signal_interval_minutes',
    label: 'Scanner signal interval',
    unit: 'minutes',
    default: 5,
    type: 'number',
    area: 'system',
    subsection: 'system-resource-tuning',
    backendSection: 'bot-operations',
    backendPath: 'scanner_signal_interval_minutes',
    description: 'Minutes between scanner signal-generation passes.',
    usedBy: ['forven.scanner', 'forven.scheduler'],
    advanced: true,
  },
  {
    id: 'bot-operations.scanner_execution_interval_minutes',
    label: 'Scanner execution interval',
    unit: 'minutes',
    default: 5,
    type: 'number',
    area: 'system',
    subsection: 'system-resource-tuning',
    backendSection: 'bot-operations',
    backendPath: 'scanner_execution_interval_minutes',
    description: 'Minutes between scanner execution passes (placing orders on signals).',
    usedBy: ['forven.scanner', 'forven.scheduler'],
    advanced: true,
  },
  {
    id: 'bot-operations.scanner_allow_direct_market_fetch',
    label: 'Scanner direct market fetch',
    default: true,
    type: 'toggle',
    area: 'system',
    subsection: 'system-resource-tuning',
    backendSection: 'bot-operations',
    backendPath: 'scanner_allow_direct_market_fetch',
    description: 'Let the scanner bypass the cache and hit the exchange directly when stale.',
    usedBy: ['forven.scanner', 'forven.market_data'],
    advanced: true,
  },
  {
    id: 'bot-operations.daemon_candle_cache_refresh_seconds',
    label: 'Candle cache refresh',
    unit: 'seconds',
    default: 90,
    type: 'number',
    area: 'system',
    subsection: 'system-resource-tuning',
    backendSection: 'bot-operations',
    backendPath: 'daemon_candle_cache_refresh_seconds',
    description: 'How often the daemon refreshes the shared candle cache.',
    usedBy: ['forven.daemon', 'forven.market_data_collector'],
    advanced: true,
  },
  {
    id: 'bot-operations.pipeline_assignments_per_cycle',
    label: 'Pipeline assignments per cycle',
    default: 5,
    type: 'number',
    area: 'system',
    subsection: 'system-resource-tuning',
    backendSection: 'bot-operations',
    backendPath: 'pipeline_assignments_per_cycle',
    description: 'Max strategies the pipeline assigns to workers per dispatch cycle.',
    usedBy: ['forven.strategy_lifecycle', 'forven.runtime_worker'],
    advanced: true,
  },
  {
    id: 'bot-operations.pipeline_drain_mode',
    label: 'Pipeline drain mode',
    default: true,
    type: 'toggle',
    area: 'system',
    subsection: 'system-resource-tuning',
    backendSection: 'bot-operations',
    backendPath: 'pipeline_drain_mode',
    description: 'Drain in-flight work before accepting new assignments during pressure.',
    usedBy: ['forven.strategy_lifecycle', 'forven.runtime_worker'],
    advanced: true,
  },
  {
    id: 'bot-operations.pipeline_drain_max_seconds',
    label: 'Pipeline drain max',
    unit: 'seconds',
    default: 300,
    type: 'number',
    area: 'system',
    subsection: 'system-resource-tuning',
    backendSection: 'bot-operations',
    backendPath: 'pipeline_drain_max_seconds',
    description: 'Hard ceiling on how long drain mode blocks new assignments.',
    usedBy: ['forven.strategy_lifecycle', 'forven.runtime_worker'],
    advanced: true,
  },
  {
    id: 'bot-operations.task_stale_recovery_minutes',
    label: 'Stale recovery window',
    unit: 'minutes',
    default: 10,
    type: 'number',
    area: 'system',
    subsection: 'system-resource-tuning',
    backendSection: 'bot-operations',
    backendPath: 'task_stale_recovery_minutes',
    description: 'Minutes after which a running task is declared stale and recovered.',
    usedBy: ['forven.phantom_recovery', 'forven.runtime_worker'],
    advanced: true,
  },
  {
    id: 'bot-operations.pipeline_gate_failure_archive_attempts',
    label: 'Gate failure archive attempts',
    default: 3,
    type: 'number',
    area: 'system',
    subsection: 'system-resource-tuning',
    backendSection: 'bot-operations',
    backendPath: 'pipeline_gate_failure_archive_attempts',
    description: 'Consecutive gate failures before a strategy is auto-archived.',
    usedBy: ['forven.strategy_lifecycle', 'forven.api_domains.tasks'],
    advanced: true,
  },
  {
    id: 'bot-operations.agent_task_claim_limit',
    label: 'Agent task claim limit',
    default: 12,
    type: 'number',
    area: 'system',
    subsection: 'system-resource-tuning',
    backendSection: 'bot-operations',
    backendPath: 'agent_task_claim_limit',
    description: 'Max agent tasks a single worker may claim per cycle.',
    usedBy: ['forven.agents.runner', 'forven.api_domains.tasks'],
    advanced: true,
  },
  {
    id: 'bot-operations.brain_task_claim_limit',
    label: 'Brain task claim limit',
    default: 12,
    type: 'number',
    area: 'system',
    subsection: 'system-resource-tuning',
    backendSection: 'bot-operations',
    backendPath: 'brain_task_claim_limit',
    description: 'Max brain tasks a single worker may claim per cycle.',
    usedBy: ['forven.brain', 'forven.api_domains.tasks'],
    advanced: true,
  },
  {
    id: 'bot-operations.code_strategy_requires_approval',
    label: 'Code strategies require approval',
    default: false,
    type: 'toggle',
    area: 'system',
    subsection: 'system-resource-tuning',
    backendSection: 'bot-operations',
    backendPath: 'code_strategy_requires_approval',
    description: 'Require a human approval before a generated strategy enters the pipeline.',
    usedBy: ['forven.control_plane.approvals', 'forven.strategy_lifecycle'],
    advanced: true,
  },
  {
    id: 'bot-operations.auto_approve_dethrone',
    label: 'Auto-approve challenger dethrones',
    default: true,
    type: 'toggle',
    area: 'system',
    subsection: 'system-resource-tuning',
    backendSection: 'bot-operations',
    backendPath: 'auto_approve_dethrone',
    description: 'When a challenger materially beats an incumbent holding a capital slot, auto-apply the dethrone so the slot frees (reversible: the incumbent is demoted paper→gauntlet). Off requires a human to approve each dethrone.',
    usedBy: ['forven.policy'],
    advanced: true,
  },
  {
    id: 'bot-operations.canonical_auto_deploy_enabled',
    label: 'Auto-deploy graduated canonical winners',
    default: false,
    type: 'toggle',
    area: 'system',
    subsection: 'system-resource-tuning',
    backendSection: 'bot-operations',
    backendPath: 'canonical_auto_deploy_enabled',
    description: 'When a hypothesis graduates, enqueue its per-cell-best (canonical) winner into the gauntlet paper-promotion gate (the robustness floor still applies). Off keeps graduation a label only.',
    usedBy: ['forven.hypothesis_graduation'],
    advanced: true,
  },
  {
    id: 'bot-operations.paper_slot_competition_enabled',
    label: 'One strategy per market (slot competition)',
    default: false,
    type: 'toggle',
    area: 'system',
    subsection: 'system-resource-tuning',
    backendSection: 'bot-operations',
    backendPath: 'paper_slot_competition_enabled',
    description: 'On: each symbol/timeframe slot holds one strategy — challengers must beat and dethrone the incumbent, and a paper count cap applies. Off (default): every strategy that passes the gauntlet is promoted to paper, no per-slot competition, no cap.',
    usedBy: ['forven.policy', 'forven.brain'],
    advanced: true,
  },
  {
    id: 'bot-operations.brain_queue_max_pending',
    label: 'Brain queue soft cap',
    default: 15,
    type: 'number',
    area: 'system',
    subsection: 'system-resource-tuning',
    backendSection: 'bot-operations',
    backendPath: 'brain_queue_max_pending',
    description: 'Soft cap on pending brain-cycle dispatches before the scheduler prunes (generic pings first; routine/operator dispatches preserved; a hard ceiling backstops).',
    usedBy: ['forven.scheduler'],
    advanced: true,
  },

  // Remote engine (system)
  {
    id: 'bot-operations.remote_engine_enabled',
    label: 'Remote engine enabled',
    default: false,
    type: 'toggle',
    area: 'system',
    subsection: 'system-remote-engine',
    backendSection: 'bot-operations',
    backendPath: 'remote_engine_enabled',
    description: 'Offload heavy backtests to a remote engine process.',
    usedBy: ['forven.routers.backtesting', 'forven.api_core'],
  },
  {
    id: 'bot-operations.remote_engine_url',
    label: 'Remote engine URL',
    default: 'http://127.0.0.1:9050',
    type: 'text',
    area: 'system',
    subsection: 'system-remote-engine',
    backendSection: 'bot-operations',
    backendPath: 'remote_engine_url',
    description: 'Base URL of the remote engine service.',
    usedBy: ['forven.routers.backtesting', 'forven.api_core'],
  },
  {
    id: 'bot-operations.remote_engine_data_root',
    label: 'Remote engine data root',
    default: '',
    type: 'text',
    area: 'system',
    subsection: 'system-remote-engine',
    backendSection: 'bot-operations',
    backendPath: 'remote_engine_data_root',
    description: 'Shared data directory the remote engine reads market data from.',
    usedBy: ['forven.routers.backtesting', 'forven.api_core'],
  },

  // Data Engine (system)
  {
    id: 'data-engine.enabled',
    label: 'Data Engine enabled',
    default: false,
    type: 'toggle',
    area: 'data',
    subsection: 'data-engine-core',
    backendSection: 'data-engine',
    backendPath: 'data_engine_settings.enabled',
    description: 'Route compatible data reads and collectors through the new DataHub path.',
    usedBy: ['forven.data', 'forven.data_manager', 'forven.dataeng.settings'],
  },
  {
    id: 'data-engine.enabled_exchanges',
    label: 'Enabled exchanges',
    default: ['binance'],
    type: 'csv',
    options: DATA_ENGINE_EXCHANGE_OPTIONS,
    area: 'data',
    subsection: 'data-engine-core',
    backendSection: 'data-engine',
    backendPath: 'data_engine_settings.enabled_exchanges',
    description: 'Exchange adapters registered by the Data Engine source registry.',
    usedBy: ['forven.dataeng.registry', 'forven.dataeng.ccxt_source'],
  },
  {
    id: 'data-engine.source_priority_candles',
    label: 'Candle source priority',
    default: ['binance'],
    type: 'csv',
    options: DATA_ENGINE_EXCHANGE_OPTIONS,
    area: 'data',
    subsection: 'data-engine-core',
    backendSection: 'data-engine',
    backendPath: 'data_engine_settings.source_priority.candles',
    description: 'Ordered source preference for OHLCV candle reads.',
    usedBy: ['forven.dataeng.registry', 'forven.dataeng.validation'],
  },
  {
    id: 'data-engine.source_priority_funding',
    label: 'Funding source priority',
    default: ['binance'],
    type: 'csv',
    options: DATA_ENGINE_EXCHANGE_OPTIONS,
    area: 'data',
    subsection: 'data-engine-core',
    backendSection: 'data-engine',
    backendPath: 'data_engine_settings.source_priority.funding',
    description: 'Ordered source preference for funding-rate data.',
    usedBy: ['forven.dataeng.registry', 'forven.data_manager'],
  },
  {
    id: 'data-engine.source_priority_oi',
    label: 'OI source priority',
    default: ['binance'],
    type: 'csv',
    options: DATA_ENGINE_EXCHANGE_OPTIONS,
    area: 'data',
    subsection: 'data-engine-core',
    backendSection: 'data-engine',
    backendPath: 'data_engine_settings.source_priority.oi',
    description: 'Ordered source preference for open-interest data.',
    usedBy: ['forven.dataeng.registry', 'forven.data_manager'],
  },
  {
    id: 'data-engine.point_in_time_mode',
    label: 'Point-in-time mode',
    default: 'latest',
    type: 'select',
    options: [
      { value: 'latest', label: 'Latest' },
      { value: 'as_of_pin', label: 'As-of pin' },
    ],
    area: 'data',
    subsection: 'data-engine-core',
    backendSection: 'data-engine',
    backendPath: 'data_engine_settings.point_in_time_mode',
    description: 'Reproducible data reads: "latest" uses current values; "as-of pin" reconstructs the values in force at the pinned timestamp below for every backtest.',
    usedBy: ['forven.dataeng.settings', 'forven.dataeng.hub', 'forven.strategies.backtest'],
  },
  {
    id: 'data-engine.point_in_time_as_of',
    label: 'Point-in-time pin',
    default: '',
    type: 'text',
    area: 'data',
    subsection: 'data-engine-core',
    backendSection: 'data-engine',
    backendPath: 'data_engine_settings.point_in_time_as_of',
    description: 'ISO-8601 timestamp (e.g. 2026-03-01T12:00:00Z) used only when point-in-time mode is "as-of pin". Backtests then read the data as it was known at this time; live reads are unaffected.',
    usedBy: ['forven.strategies.backtest', 'forven.dataeng.settings'],
  },
  {
    id: 'data-engine.auto_catchup_enabled',
    label: 'Auto catch-up',
    default: true,
    type: 'toggle',
    area: 'data',
    subsection: 'data-engine-core',
    backendSection: 'data-engine',
    backendPath: 'data_engine_settings.auto_catchup_enabled',
    description:
      'Run a background job every 10 min that drains the backfill plan, keeping the whole catalog current automatically (not just the active keep-alive set). Turn off to only catch up manually.',
    usedBy: ['forven.scheduler', 'forven.api_domains.data'],
  },
  {
    id: 'data-engine.auto_catchup_batch',
    label: 'Auto catch-up batch',
    unit: 'series/run',
    default: 12,
    type: 'number',
    area: 'data',
    subsection: 'data-engine-core',
    backendSection: 'data-engine',
    backendPath: 'data_engine_settings.auto_catchup_batch',
    description:
      'Max candle series the auto catch-up refreshes per 10-min run. Higher drains a backlog faster but makes more exchange API calls.',
    usedBy: ['forven.scheduler', 'forven.api_domains.data'],
  },
  {
    id: 'data-engine.onchain_provider',
    label: 'On-chain provider',
    default: '',
    type: 'select',
    // Only adapters implemented in forven.dataeng.onchain — anything else is
    // rejected at fetch time, so free text here just deferred the error.
    options: [
      { value: '', label: 'Disabled' },
      { value: 'coingecko-pro', label: 'CoinGecko Pro' },
    ],
    area: 'data',
    subsection: 'data-engine-core',
    backendSection: 'data-engine',
    backendPath: 'data_engine_settings.onchain_provider',
    description: 'On-chain data provider adapter. Requires the API key below when enabled.',
    usedBy: ['forven.dataeng.onchain', 'forven.dataeng.settings'],
  },
  {
    id: 'data-engine.onchain_api_key',
    label: 'On-chain API key',
    default: '',
    type: 'secret',
    area: 'data',
    subsection: 'data-engine-core',
    backendSection: 'data-engine',
    backendPath: 'data_engine_settings.onchain_api_key',
    description: 'API key used by the optional on-chain provider adapter.',
    usedBy: ['forven.dataeng.onchain', 'forven.dataeng.settings'],
  },
  {
    id: 'data-engine.source_reconciliation_enabled',
    label: 'Source reconciliation gate',
    default: false,
    type: 'toggle',
    area: 'data',
    subsection: 'data-engine-core',
    backendSection: 'data-engine',
    backendPath: 'data_engine_settings.source_reconciliation.enabled',
    description:
      'Block promotion into paper/live when the backtest price source diverges from the live trade venue beyond the threshold below. Divergence is pre-computed out-of-band by the source-reconciliation job.',
    usedBy: ['forven.policy', 'forven.source_reconciliation'],
  },
  {
    id: 'data-engine.source_reconciliation_max_divergence_pct',
    label: 'Max source divergence',
    unit: '%',
    default: 2.0,
    type: 'number',
    area: 'data',
    subsection: 'data-engine-core',
    backendSection: 'data-engine',
    backendPath: 'data_engine_settings.source_reconciliation.max_divergence_pct',
    description:
      'Worst-bar close-price divergence (backtest source vs live venue) tolerated before the reconciliation gate refuses promotion.',
    usedBy: ['forven.policy', 'forven.source_reconciliation'],
  },
  {
    id: 'data-engine.source_reconciliation_block_when_missing',
    label: 'Block when divergence unknown',
    default: false,
    type: 'toggle',
    area: 'data',
    subsection: 'data-engine-core',
    backendSection: 'data-engine',
    backendPath: 'data_engine_settings.source_reconciliation.block_when_missing',
    description:
      'When on, a strategy with no (or stale) computed divergence is held out of paper/live instead of being allowed through. Off keeps the funnel fail-open.',
    usedBy: ['forven.policy', 'forven.source_reconciliation'],
  },

  // -------------------- SYSTEM: API KEYS --------------------
  {
    id: 'api-keys.tiingo',
    label: 'Tiingo API key',
    default: '',
    type: 'secret',
    area: 'system',
    subsection: 'system-api-keys',
    backendSection: 'api-keys',
    backendPath: 'tiingo',
    description: 'API key for Tiingo market-data endpoints.',
    usedBy: ['forven.data_manager', 'forven.api_core'],
  },
  {
    id: 'api-keys.fred',
    label: 'FRED API key',
    default: '',
    type: 'secret',
    area: 'system',
    subsection: 'system-api-keys',
    backendSection: 'api-keys',
    backendPath: 'fred',
    description: 'API key for FRED macroeconomic series.',
    usedBy: ['forven.data_manager', 'forven.api_core'],
  },
  {
    id: 'api-keys.coingecko',
    label: 'CoinGecko API key',
    default: '',
    type: 'secret',
    area: 'system',
    subsection: 'system-api-keys',
    backendSection: 'api-keys',
    backendPath: 'coingecko',
    description: 'API key for CoinGecko data.',
    usedBy: ['forven.data_manager', 'forven.api_core'],
  },
  {
    id: 'api-keys.polygon',
    label: 'Polygon API key',
    default: '',
    type: 'secret',
    area: 'system',
    subsection: 'system-api-keys',
    backendSection: 'api-keys',
    backendPath: 'polygon',
    description: 'API key for Polygon.io market data.',
    usedBy: ['forven.data_manager', 'forven.api_core'],
  },
  {
    id: 'api-keys.alpaca',
    label: 'Alpaca API key',
    default: '',
    type: 'secret',
    area: 'system',
    subsection: 'system-api-keys',
    backendSection: 'api-keys',
    backendPath: 'alpaca',
    description: 'API key for Alpaca broker/data endpoints.',
    usedBy: ['forven.data_manager', 'forven.api_core'],
  },

  // -------------------- SYSTEM: TELEMETRY --------------------
  // No manifest-backed telemetry flags yet. Additional telemetry flags can be
  // added here as the backend exposes them.

  // -------------------- SYSTEM: DATABASE MAINTENANCE --------------------
  // These live in the pipeline settings payload (forven:pipeline:settings) and
  // round-trip via PUT /api/pipeline/settings (backendSection 'pipeline'). A
  // retention value of 0 disables pruning for that table.
  {
    id: 'pipeline.retention_backtest_trash_days',
    label: 'Backtest trash retention',
    unit: 'days',
    default: 14,
    type: 'number',
    area: 'system',
    subsection: 'system-db-maintenance',
    backendSection: 'pipeline',
    backendPath: 'retention_backtest_trash_days',
    description: 'Days to keep trashed/deleted backtest results before they are hard-deleted. 0 disables pruning.',
    usedBy: ['forven.maintenance', 'forven.api_core'],
  },
  {
    id: 'pipeline.retention_activity_log_days',
    label: 'Activity log retention',
    unit: 'days',
    default: 90,
    type: 'number',
    area: 'system',
    subsection: 'system-db-maintenance',
    backendSection: 'pipeline',
    backendPath: 'retention_activity_log_days',
    description: 'Days to keep activity_log rows before pruning. 0 disables pruning.',
    usedBy: ['forven.maintenance', 'forven.api_core'],
  },
  {
    id: 'pipeline.retention_scanner_results_days',
    label: 'Scanner results retention',
    unit: 'days',
    default: 30,
    type: 'number',
    area: 'system',
    subsection: 'system-db-maintenance',
    backendSection: 'pipeline',
    backendPath: 'retention_scanner_results_days',
    description: 'Days to keep scanner_signal_results rows before pruning. 0 disables pruning.',
    usedBy: ['forven.maintenance', 'forven.api_core'],
  },
  {
    id: 'pipeline.retention_gate_rejections_days',
    label: 'Gate rejections retention',
    unit: 'days',
    default: 30,
    type: 'number',
    area: 'system',
    subsection: 'system-db-maintenance',
    backendSection: 'pipeline',
    backendPath: 'retention_gate_rejections_days',
    description: 'Days to keep gate_rejections rows before pruning. 0 disables pruning.',
    usedBy: ['forven.maintenance', 'forven.api_core'],
  },
  {
    id: 'pipeline.maintenance_vacuum_enabled',
    label: 'Daily VACUUM',
    default: false,
    type: 'toggle',
    area: 'system',
    subsection: 'system-db-maintenance',
    backendSection: 'pipeline',
    backendPath: 'maintenance_vacuum_enabled',
    description: 'Run VACUUM during the daily DB maintenance job to reclaim disk space. Heavy operation — off by default.',
    usedBy: ['forven.maintenance', 'forven.api_core'],
  },

  // -------------------- DANGER --------------------
  // The Danger Zone (factory reset) is a custom destructive-action component
  // (SettingsDangerZone.svelte): it loads the category catalog, lets the operator
  // choose which categories to KEEP, and executes behind a typed confirmation. It
  // calls POST /api/system/factory-reset directly, so it has no flat-settings rows.
];
